# UNIT I

## MODULE 1
## TOPIC : Introduction to python

#### QUESTION 1

Perform Caesar Cipher technique

As input, give a String and a constant integer value. Find the encrypted text message for each of the following Strings.

Rules for the encryption are, for each character in string shift the character to the right of a specific fixed value that you are given as the input.
 
#### E(x) = (x + n) mod(26)


Input Format
    
    First line of input consist of String that you want to encrypt.

    Second line of the input consist of a fixed integer value to shift.
Output Format
    
    Output consist of Encrypted string.
Constraints
    
    0 < n < âˆž

Sample Input 1
    
    This is the secret message
    10
Sample Output 1
    
    Drscxscxdroxcombodxwocckqo

In [ ]:
def encrypt(text,val):
    result = ""

    for i in range(len(text)):
        char = text[i]

        if (char.isupper()):
            result += chr((ord(char) + val-65) % 26 + 65)

        else:
            result += chr((ord(char) + val - 97) % 26 + 97)

    return result

text = input()
val = int(input())

print(encrypt(text,val))

#### QUESTION 2

Given an array of integers num and an integer target, return indices of the two numbers such that the multiple is up to target.
<br>
You may assume that each input would have exactly one solution, and you may not use the same element twice.
<br>
You can return the answer in any order.
<br>

Input Format

    First line of input should be the number of elements in a list
Second line of the input should be a list of n natural values
    
    Third line of input should be the target value
Output Format
    
    The first line of output will be in a list
Constraints
    
    list should have n number of values
Sample Input 1

    5
    1 2 3 4 5
    3
Sample Output 1
    
    [0, 2]
Sample Input 2
    
    8 
    12 23 21 23 43 21 1 23
    23 
Sample Output 2

    [1, 6]

In [ ]:
def encrypt(text,val):
    result = ""

    for i in range(len(text)):
        char = text[i]

        if (char.isupper()):
            result += chr((ord(char) + val-65) % 26 + 65)

        else:
            result += chr((ord(char) + val - 97) % 26 + 97)

    return result

text = input()
val = int(input())

print(encrypt(text,val))

#### QUESTION 3

Construct a main class called Rectangle that has the attributes length and width.

Create methods for calculating the area and the perimeter.

Have a display function to display length, width, perimeter, area.

Create a child class called Parallelepiped child class, give height as a attribute, and include a volume method to get its volume.


Input Format
    
    First line of input has length

    Second line of input has width

    Third line of input has the height
    
Output Format
    
    first line returns (length, width, perimeter, area) in a tuple

    second line returns the volume of the parallelepiped
Constraints
    
    The entered value should be in positive range
Sample Input 1
    
    2
    5
    7
Sample Output 1
    
    (2, 5, 14, 10)
    70

In [ ]:
class Rectangle :
    def __init__(self,length,width) :
        self.length = length
        self.width = width

    def Perimeter(self):
        return 2*(self.length + self.width);

    def Area(self):
        return self.length * self.width ;

    def display(self):
        return self.length ,self.width ,self.Perimeter() ,self.Area();

class Parallelepipede(Rectangle):
    def __init__(self, length, width,height):
        super().__init__(length, width)
        self.height = height
    def volume(self):
        return self.height*self.length*self.width

length = int(input())
width = int(input())
height = int(input())

r = Parallelepipede(length,width,height)
print(r.display())
print(r.volume())

#### QUESTION 4

Write a program to calculate the BMI of a person using class. The height and weight should be the input. Create an exception name NegativeError if the user enters a negative value for his height or weight. Display the BMI of the person.
    
    
    {BMI} = {weight}/{height}^2

Note :
    
    Weight should be in kg
    
    Height should be in metres
    
Input format:
    
    First line of input has weight
    
    Second line of input has height
    
Output format:
    
    first line returns the BMI of the person
    
Sample input 1:
    
    68
    1.65
    
Sample Output 1
    
    24.98
    
Sample input 2:
    
    6
    1.56
    
Sample Output 2:
    
    The value you entered is negative

In [ ]:
class NegativeError(Exception):
    """ Raised when the input value is negative """
    pass


class BMI:
    def __init__(self,w,h) :
        self.weight = w
        self.height = h
    
    def calculate(self):

        return '%.2f' %(self.weight/self.height**2);

while (True):
    try:
        w = float(input()) #in kg
        h = float(input()) #in m

        if w < 0 or h < 0 :
            raise NegativeError
        

        break
    except NegativeError:
        print("The value you entered is negative")

o = BMI(w,h)
print(o.calculate())

#### QUESTION 5

Create a pascal triangle by getting the number of rows as an input.
    
Pascal Triangle concept:
    
Each number is the sum of the two numbers directly above it 
    
                                        1
    
                                1                 1
    
                      1                 2                 1
    
             1              3                     3              1
    
        1          4                   6                  4            1
    
Input Format 
    
    First line of input is no of rows.
    
Output Format 
    
    The output should be in list for each row
    
Sample input 1
    
    3
    [[1], [1, 1], [1, 2, 1]]
    
Sample input 2
    
    5
    [[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]

In [ ]:
def Pascal(rows):
    List = [0]*rows
    for i in range(rows):
        if i == 0:
            List[i] = [1]
        elif i== 1:
            List[i] = [1,1]
        else:
            List[i] = [0]*(i+1)
            List[i][0] = List[i][i] = 1
            for j in range(1,i):
                List[i][j] = List[i-1][j-1]+List[i-1][j]
    return List

n = int (input())
print (Pascal(n))

#### QUESTION 6

6. Create a database of the following table in sqlite.
    
    Table name = Movies
    
    | movie_id(int) | movie_name (char) | movie_dir (char) | rating(float) |
    | --- | --- | --- | --- |
    | 1 | Avatar | James Cameron | 7.9 |
    | 2 | Inception | Nolan | 8.5 |
    | 3 | Top Gun Maverick | Joseph Kosinski | 8.4 |
    | 4 | Batman | Matt Reeves | 7.8 |
    | 5 | Ready Player One | Steven Spielberg | 7.4 |
    
    1. Create the above mentioned table
    2. Select all rows from the table and display it.

In [ ]:
import sqlite3

from sqlite3 import Error

def sql_connection():
	try:
		conn = sqlite3.connect('mydatabase.db')
		return conn
	except Error:
		 print(Error)

def sql_table(conn):
	cursorObj = conn.cursor()
	# Create the table
	cursorObj.execute("CREATE TABLE Movies(movie_id n(5), movie_name char(30), movie_dir char(35), rating float);")
	# Insert records
	cursorObj.executescript("""
	   INSERT INTO Movies VALUES(1,'Avatar','James Cameron',7.9);
	   INSERT INTO Movies VALUES(2,'Inception','Nolan',8.5);
	   INSERT INTO Movies VALUES(3,'Top Gun Maverick', 'Joseph Kosinski', 8.4);
	   INSERT INTO Movies VALUES(4,'Batman', 'Matt Reeves', 7.8);
	   INSERT INTO Movies VALUES(5,'Ready Player One', 'Steven Spielberg', 7.4);
	   """)
	conn.commit()   
	cursorObj.execute("SELECT * FROM Movies")
	rows = cursorObj.fetchall()
	print("Agent details:")
	for row in rows:
		   print(row)
sqllite_conn = sql_connection()
sql_table(sqllite_conn)
if (sqllite_conn):
	 sqllite_conn.close()
print("\nThe SQLite connection is closed.")

#### QUESTION 7

Display the following pattern 
        
        5 4 3 2 1 1 2 3 4 5 
        5 4 3 2     2 3 4 5 
        5 4 3         3 4 5 
        5 4             4 5 
        5                 5
Input Format:
    
    Enter the number
    
Output Format:
    
    Prints the pattern according to it

Sample input
    
    6
    
Sample Output
    
    5 4 3 2 1 1 2 3 4 5 
    5 4 3 2     2 3 4 5 
    5 4 3         3 4 5 
    5 4             4 5 
    5                 5

In [ ]:
rows = int(input())
for i in range(0, rows):
    for j in range(rows - 1, i, -1):
        print(j, '', end='')
    for l in range(i):
        print('    ', end='')
    for k in range(i + 1, rows):
        print(k, '', end='')
    print('\n')

### QUESTION 8

You are joining a bank and you are assigned a task to write a program to return the balance from of a user by giving their transaction log.
    
The input format should be like
    
    D 100 
    W 150
    
    D - Deposit
    
    W - Withdraw
    
Sample input :
    
    D 300 
    
    D 300 
    
    W 200 
    
    D 100
    
Sample Output:
    
    500

In [ ]:
count = 0
while True:
    s = input()
    
    if not s:
        break
    values = s.split(" ")
    operation = values[0]
    amount = int(values[1])

    if operation=="D" or operation == 'd':
        count+=amount
    elif operation=="W" or operation == 'w':
        count-=amount
    else:
        pass
print(count)

#### QUESTION 9

You are given a task as a programmer to remove the duplication of words in a sentences and returning the non duplicated string back.
    
Input Format
    
    First line consist of the input string
    
Output Format:
    
    First line consist of non duplicated string
    
Sample input:
    
    hi how are you you
    
    Sample output:
    
    hi how are you
    
    code:

In [ ]:
def remove_duplicate(your_str):
   result = ''
   str1 = your_str.split()
   print(str1)
   for char in str1:
       if char not in result:
           result += char+ ' '
           
   return result
 
user_input = input('what is your string:')
 
no_duplicate = remove_duplicate(user_input)
print('Without duplicate: ', no_duplicate)

#### QUESTION 10

We all know that computer understands the characters in 0â€™s and 1â€™s (binary). So your task is to convert a decimal number from the input to a binary number.
    
Input format:
    
    First line of input consist of the decimal number 
    
Output format:
    
    The first line consist of the binary equivalent of the decimal number.
    
Sample input:
    
    85
    
Sample output:
    
    1010101

In [ ]:
def dec_to_binary(n):
	bits = []
	
	while n > 0:
		bits.append(n%2)
		n = n // 2
	bits.reverse()
	
	binary = ''
	for bit in bits:
		binary += str(bit)
	return binary


num = int(input())
binary = dec_to_binary(num)
print(binary)

#### QUESTION 11

Create a class Employee: and add salary and increment properties to it. Write a getter method getSalary() and setter setSalary() which changes the value of increment based on the salary?

Input Format
    
    First line of input consist of basic salary

    Second line of input consist of old increment

    Third line of input consist of new gross salary
Output Format

    First line of output consist of calculation of old gross salary

    Second line of output consist of the basic salary

    Third line of output consist of the updated increment
Constraints

    Entering amount should be positive
Sample Input 1
    
    5000
    600
    7500
Sample Output 1

    7500
    5000
    2500

In [ ]:
class Employee:
    def __init__(self, salary, increment):
        self.salary = salary
        self.increment = increment

    @property
    def getSalary(self):
        return self.salary + self.increment


    @getSalary.setter
    def setSalary(self, newSalary):
        self.increment = newSalary- self.salary
s = int(input())
i = int(input())
emp = Employee(s,i)
emp.setSalary = int(input())


print(emp.getSalary)  
print(emp.salary)
print(emp.increment)

#### QUESTION 12

Draw a program to replicate the following pattern

                                                            *
													      *   *
													    *       *
													  *           *
													*               *
													  *           *
													    *       *
													      *   *
														    *
                                                            
Input format

    First line consist of the number of rows.

Output

    The pattern 
Sample Input 1
    
    5
Sample Output 1

                                                            *
													      *   *
													    *       *
													  *           *
													*               *
													  *           *
													    *       *
													      *   *
														    *

In [ ]:
rows = int(input())
i = 1
while i <= rows:
    j = rows
    while j > i:
        print(' ', end=' ')
        j -= 1
    print('*', end=' ')
    k = 1
    while k < 2 * (i - 1):
        print(' ', end=' ')
        k += 1
    if i == 1:
        print()
    else:
        print('*')
    i += 1

i = rows - 1
while i >= 1:
    j = rows
    while j > i:
        print(' ', end=' ')
        j -= 1
    print('*', end=' ')
    k = 1
    while k <= 2 * (i - 1)-1:
        print(' ', end=' ')
        k += 1
    if i == 1:
        print()
    else:
        print('*')
    i -= 1

#### QUESTION 13

13. Create a deck of cards class. Internally, the deck of cards should use another class, a card class. Your requirements are:
    
    - TheÂ **deck**Â class should have aÂ **deal**Â method to deal a single card from the deck
    - After a card is dealt, it is removed from the deck.
    - There should be aÂ **shuffle**Â method which makes sure the deck of cards has all 52 cards and then rearranges them randomly.
    - TheÂ **card**Â class should have a suit (Hearts, Diamonds, Clubs, Spades) and a value (A, 2, 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K)

In [ ]:
from random import shuffle

class Card:
	def __init__(self, suit, value):
		self.suit = suit
		self.value = value

	def __repr__(self):
		return "{} of {}".format(self.value, self.suit)

class Deck:
	def __init__(self):
		suits = ['Hearts','Diamonds','Clubs','Spades'] 
		values = ['A','2','3','4','5','6','7','8','9','10','J','Q','K']
		self.cards = [Card(suit, value) for suit in suits for value in values]
        
	def __repr__(self):
		return "Cards remaining in deck: {}".format(len(self.cards))

	def shuffle(self):
		if len(self.cards) < 52:
			raise ValueError("Only full decks can be shuffled")
		shuffle(self.cards)
		return self

	def deal(self):
		if len(self.cards) == 0:
			raise ValueError("All cards have been dealt")
		return self.cards.pop()

c= Card('Hearts','7')
d = Deck()
print(d.cards)
print(d.shuffle())
print(d.cards)
print(d.deal())
print(d.cards)

#### QUESTION 14

Your task is to find the sum of length of the names of a given list of names after removing the names that starts with a lowercase letters or contains any lower case letters. Use lambda function.

Input Format
    
    First line of input consist of number of elements on the list
    Second line consist of values entered in the list
Output Format
    
    First line consist of the final sum value
Sample Input 1

    3
    HI No wow
Sample Output 1
    
    2
Sample Input 2
    
    6
    varun Tarun VICKY hi HI No 
Sample Output 2
    
    7

In [ ]:
n = int(input()) 
sample_names = list(map(str,input().strip().split()))[:n] 
sample_names=list(filter(lambda el:el[0].isupper() and el[1:].isupper(),sample_names))
print(len(''.join(sample_names)))

#### QUESTION 15

The longest common subsequence (LCS) is defined as the longest subsequence that is common to all the given sequences, provided that the elements of the subsequence are not required to occupy consecutive positions within the original sequences.
<br>
Implement a code using recursion to find the length of the least common subsequence (lcs).

Input Format
    
    First line consist of the string
    Second line consist of another string
Output Format
    
    Returns the length of the lcd
Sample Input 1
    
    abcdef
    abcdfghij
Sample Output 1
    
    5

In [ ]:
def lcs(X, Y, m, n):
 
    if m == 0 or n == 0:
       return 0;
    elif X[m-1] == Y[n-1]:
       return 1 + lcs(X, Y, m-1, n-1);
    else:
       return max(lcs(X, Y, m, n-1), lcs(X, Y, m-1, n));
 
 
X = input()
Y = input()
print (lcs(X, Y, len(X), len(Y)))

#### QUESTION 16

Create a programme that identify the common substring among all the strings in an array. Use functions to do so.

Input Format
    
    Enter the list of values from user
Output Format
    
    Returns the common sequence.
Sample Input 1
    
    example ex exclamation expect
Sample Output 1
    
    ex

In [ ]:
def longest_common_prefix(strings):
  if not strings:
    return ''
  
  for i, chars in enumerate(zip(*strings)):
    if len(set(chars)) > 1:
      return strings[0][:i]
  else:
    return min(strings)

strings =   list(map(str,input().strip().split()))
print(longest_common_prefix(strings))

***